### ISSUE TITLE
Need a way to handle "walk-up" registrations at the beginning of a session.

### ISSUE THREAD

**Issue by aaronstine** [13gne/shcoderdojo#20]
We know that there are likely parents / Ninja who will show up at a session but have no previously registered for that session. We need some way to expediently get those people registered on the day they arrive.

Currently the process requires them to enter an email address and password. That can probably be done immediately.

Then they must confirm their email address. This _may_ be a challenge for people who don't have access to their email on their phone. **Is there a workaround we can put in place to enable the registration process to move ahead if the user doesn't have access to email at the time**?

Open to any suggestions on the best way to handle this use case.

**Comment by moottoast** [comment]
I don't know. We'd probably want the parent/student to complete the registration process themselves, otherwise we'd risk short-circuiting the information gathering and student registration process. I would imagine any parent/student pair showing up to CoderDojo would need to have access to their email to register for Scratch or CodeAnywhere or whatever other service they would need to have access during the session.

I would recommend that anyone who shows up without being registered be asked to sit down and complete the registration on their own. Thoughts?

**Comment by aaronstine** [comment]
All good points. We'll try having people register online today and see how it goes. Could be a non-issue.

**Comment by NovaG8r** [comment]
That did seem to work out pretty well on Monday.  The parents could access their email on their phones and were able to register while there.  Potentially a non-issue at this point.
