### ISSUE TITLE
Problems with Creating new courses

### ISSUE THREAD

**Issue by NovaG8r** [13gne/shcoderdojo#39]
It appears that the Summer 2017 HTML course somehow shows that 3 people are already enrolled even tho it is not published yet.  Actually, it appears that this course superseded the original Spring Course and kept the three people who were signed up (and Rhea Varghese shouldn't even be on it at this time). It is probably something that I did wrong, but  the ability to fix it is beyond my control.  I was trying to get the new courses set up and available to the public by Monday.

**Comment by moottoast** [comment]
@NovaG8r, I'm not sure what you did, but the spring HTML CSS course is gone. Did you inadvertently change it into the summer course instead of creating a new one?

**Comment by NovaG8r** [comment]
I didn't think so, but it sure looks like I did!  I thought I copied the
description and pasted it into a new course, but I could have been
multitasking and just gone back to existing course thinking I was in new
one!  What should I do to fix it?


Nancy

Nancy Vellucci
nvellucci@gmail.com

**Comment by aaronstine** [comment]
Ok, I just completed updating the Summer Scratch course (with dates, resources, etc.) Afterwards, I clicked the "Published" checkbox and it disappeared from the list.

@moottoast Can you validate that it's still in the DB or is it actually deleted?

**Comment by moottoast** [comment]
@aaronstine, There's an additional field I was using to hide the courses that we no longer relevant called `current` that defaulted to `NULL`. I fixed for the summer Scratch course. Also, the `created_at` date of the summer's HTML course is from the beginning of March, leading me to believe that a new course was not created, rather spring's HTML course was mistakenly edited to be the summer's. That's why @NovaG8r saw registrations. You'll probably want to put it back and create a new course for the summer.
